// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, key_prefix)
VALUES ($1, $2)
RETURNING id, key_hash, key_prefix, created_at
`

type CreateAPIKeyParams struct {
	KeyHash   string `json:"key_hash"`
	KeyPrefix string `json:"key_prefix"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.KeyHash, arg.KeyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllAPIKeys = `-- name: DeleteAllAPIKeys :exec
DELETE FROM api_keys
`

func (q *Queries) DeleteAllAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAPIKeys)
	return err
}

const getLatestAPIKey = `-- name: GetLatestAPIKey :one
SELECT id, key_hash, key_prefix, created_at FROM api_keys ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestAPIKey(ctx context.Context) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getLatestAPIKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
	)
	return i, err
}
