// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_recipients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateCampaignRecipientsParams struct {
	CampaignID   pgtype.UUID `json:"campaign_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

const countRecipientsByStatus = `-- name: CountRecipientsByStatus :one
SELECT COUNT(*) FROM campaign_recipients
WHERE campaign_id = $1 AND status = $2
`

type CountRecipientsByStatusParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Status     string      `json:"status"`
}

func (q *Queries) CountRecipientsByStatus(ctx context.Context, arg CountRecipientsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipientsByStatus, arg.CampaignID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalSent = `-- name: CountTotalSent :one
SELECT COUNT(*) FROM campaign_recipients WHERE status = 'sent'
`

func (q *Queries) CountTotalSent(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalSent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaignRecipient = `-- name: CreateCampaignRecipient :one
INSERT INTO campaign_recipients (campaign_id, subscriber_id)
VALUES ($1, $2)
RETURNING id, campaign_id, subscriber_id, status, sent_at
`

type CreateCampaignRecipientParams struct {
	CampaignID   pgtype.UUID `json:"campaign_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) CreateCampaignRecipient(ctx context.Context, arg CreateCampaignRecipientParams) (CampaignRecipient, error) {
	row := q.db.QueryRow(ctx, createCampaignRecipient, arg.CampaignID, arg.SubscriberID)
	var i CampaignRecipient
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SubscriberID,
		&i.Status,
		&i.SentAt,
	)
	return i, err
}

const getRecipientStatus = `-- name: GetRecipientStatus :one
SELECT status FROM campaign_recipients
WHERE campaign_id = $1 AND subscriber_id = $2
`

type GetRecipientStatusParams struct {
	CampaignID   pgtype.UUID `json:"campaign_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) GetRecipientStatus(ctx context.Context, arg GetRecipientStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getRecipientStatus, arg.CampaignID, arg.SubscriberID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listCampaignsReceivedBySubscriber = `-- name: ListCampaignsReceivedBySubscriber :many
SELECT c.id, c.name, c.subject, c.preview_text, c.from_name, c.from_email, c.reply_to,
       c.html_body, c.text_body, c.status, c.send_to_type, c.send_to_id,
       c.scheduled_at, c.sent_at, c.created_at, c.updated_at
FROM campaigns c
JOIN campaign_recipients cr ON cr.campaign_id = c.id
WHERE cr.subscriber_id = $1
ORDER BY cr.sent_at DESC NULLS LAST
`

func (q *Queries) ListCampaignsReceivedBySubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsReceivedBySubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
			&i.SendToType,
			&i.SendToID,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRecipients = `-- name: ListPendingRecipients :many
SELECT id, campaign_id, subscriber_id, status, sent_at FROM campaign_recipients
WHERE campaign_id = $1 AND status = 'pending'
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListPendingRecipientsParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListPendingRecipients(ctx context.Context, arg ListPendingRecipientsParams) ([]CampaignRecipient, error) {
	rows, err := q.db.Query(ctx, listPendingRecipients, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignRecipient
	for rows.Next() {
		var i CampaignRecipient
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SubscriberID,
			&i.Status,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipientStatus = `-- name: UpdateRecipientStatus :exec
UPDATE campaign_recipients SET status = $3, sent_at = $4
WHERE campaign_id = $1 AND subscriber_id = $2
`

type UpdateRecipientStatusParams struct {
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	SubscriberID pgtype.UUID        `json:"subscriber_id"`
	Status       string             `json:"status"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) UpdateRecipientStatus(ctx context.Context, arg UpdateRecipientStatusParams) error {
	_, err := q.db.Exec(ctx, updateRecipientStatus,
		arg.CampaignID,
		arg.SubscriberID,
		arg.Status,
		arg.SentAt,
	)
	return err
}
