// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCampaign = `-- name: CancelCampaign :one
UPDATE campaigns
SET status = 'draft', scheduled_at = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at
`

func (q *Queries) CancelCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, cancelCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.SendToType,
		&i.SendToID,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCampaigns = `-- name: CountCampaigns :one
SELECT COUNT(*) FROM campaigns
`

func (q *Queries) CountCampaigns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaigns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCampaignsByStatus = `-- name: CountCampaignsByStatus :one
SELECT COUNT(*) FROM campaigns WHERE status = $1
`

func (q *Queries) CountCampaignsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, send_to_type, send_to_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at
`

type CreateCampaignParams struct {
	Name        string      `json:"name"`
	Subject     string      `json:"subject"`
	PreviewText string      `json:"preview_text"`
	FromName    string      `json:"from_name"`
	FromEmail   string      `json:"from_email"`
	ReplyTo     string      `json:"reply_to"`
	HtmlBody    string      `json:"html_body"`
	TextBody    string      `json:"text_body"`
	SendToType  string      `json:"send_to_type"`
	SendToID    pgtype.UUID `json:"send_to_id"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.Subject,
		arg.PreviewText,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.HtmlBody,
		arg.TextBody,
		arg.SendToType,
		arg.SendToID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.SendToType,
		&i.SendToID,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.SendToType,
		&i.SendToID,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at FROM campaigns ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
			&i.SendToType,
			&i.SendToID,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByStatus = `-- name: ListCampaignsByStatus :many
SELECT id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at FROM campaigns
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListCampaignsByStatus(ctx context.Context, arg ListCampaignsByStatusParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
			&i.SendToType,
			&i.SendToID,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledCampaignsDue = `-- name: ListScheduledCampaignsDue :many
SELECT id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at FROM campaigns
WHERE status = 'scheduled' AND scheduled_at <= NOW()
`

func (q *Queries) ListScheduledCampaignsDue(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listScheduledCampaignsDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
			&i.SendToType,
			&i.SendToID,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignSent = `-- name: MarkCampaignSent :exec
UPDATE campaigns
SET status = 'sent', sent_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkCampaignSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCampaignSent, id)
	return err
}

const scheduleCampaign = `-- name: ScheduleCampaign :one
UPDATE campaigns
SET status = 'scheduled', scheduled_at = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at
`

type ScheduleCampaignParams struct {
	ID          pgtype.UUID        `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) ScheduleCampaign(ctx context.Context, arg ScheduleCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, scheduleCampaign, arg.ID, arg.ScheduledAt)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.SendToType,
		&i.SendToID,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
    name         = $2,
    subject      = $3,
    preview_text = $4,
    from_name    = $5,
    from_email   = $6,
    reply_to     = $7,
    html_body    = $8,
    text_body    = $9,
    send_to_type = $10,
    send_to_id   = $11,
    scheduled_at = $12,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, name, subject, preview_text, from_name, from_email, reply_to, html_body, text_body, status, send_to_type, send_to_id, scheduled_at, sent_at, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Subject     string             `json:"subject"`
	PreviewText string             `json:"preview_text"`
	FromName    string             `json:"from_name"`
	FromEmail   string             `json:"from_email"`
	ReplyTo     string             `json:"reply_to"`
	HtmlBody    string             `json:"html_body"`
	TextBody    string             `json:"text_body"`
	SendToType  string             `json:"send_to_type"`
	SendToID    pgtype.UUID        `json:"send_to_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.Subject,
		arg.PreviewText,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.HtmlBody,
		arg.TextBody,
		arg.SendToType,
		arg.SendToID,
		arg.ScheduledAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.SendToType,
		&i.SendToID,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaigns SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStatus, arg.ID, arg.Status)
	return err
}
