// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClicksByCampaign = `-- name: CountClicksByCampaign :one
SELECT COUNT(*) FROM clicks WHERE campaign_id = $1
`

func (q *Queries) CountClicksByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClicksByLink = `-- name: CountClicksByLink :many
SELECT link_index, link_url, COUNT(*) AS click_count
FROM clicks
WHERE campaign_id = $1
GROUP BY link_index, link_url
ORDER BY link_index
`

type CountClicksByLinkRow struct {
	LinkIndex  int32  `json:"link_index"`
	LinkUrl    string `json:"link_url"`
	ClickCount int64  `json:"click_count"`
}

func (q *Queries) CountClicksByLink(ctx context.Context, campaignID pgtype.UUID) ([]CountClicksByLinkRow, error) {
	rows, err := q.db.Query(ctx, countClicksByLink, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountClicksByLinkRow
	for rows.Next() {
		var i CountClicksByLinkRow
		if err := rows.Scan(&i.LinkIndex, &i.LinkUrl, &i.ClickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTotalClicks = `-- name: CountTotalClicks :one
SELECT COUNT(*) FROM clicks
`

func (q *Queries) CountTotalClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalClicks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listClicksBySubscriber = `-- name: ListClicksBySubscriber :many
SELECT id, campaign_id, subscriber_id, link_index, link_url, clicked_at FROM clicks WHERE subscriber_id = $1 ORDER BY clicked_at DESC
`

func (q *Queries) ListClicksBySubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]Click, error) {
	rows, err := q.db.Query(ctx, listClicksBySubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SubscriberID,
			&i.LinkIndex,
			&i.LinkUrl,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordClick = `-- name: RecordClick :one
INSERT INTO clicks (campaign_id, subscriber_id, link_index, link_url)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, subscriber_id, link_index, link_url, clicked_at
`

type RecordClickParams struct {
	CampaignID   pgtype.UUID `json:"campaign_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
	LinkIndex    int32       `json:"link_index"`
	LinkUrl      string      `json:"link_url"`
}

func (q *Queries) RecordClick(ctx context.Context, arg RecordClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, recordClick,
		arg.CampaignID,
		arg.SubscriberID,
		arg.LinkIndex,
		arg.LinkUrl,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SubscriberID,
		&i.LinkIndex,
		&i.LinkUrl,
		&i.ClickedAt,
	)
	return i, err
}
