// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateCampaignRecipients implements pgx.CopyFromSource.
type iteratorForBulkCreateCampaignRecipients struct {
	rows                 []BulkCreateCampaignRecipientsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateCampaignRecipients) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateCampaignRecipients) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CampaignID,
		r.rows[0].SubscriberID,
	}, nil
}

func (r iteratorForBulkCreateCampaignRecipients) Err() error {
	return nil
}

func (q *Queries) BulkCreateCampaignRecipients(ctx context.Context, arg []BulkCreateCampaignRecipientsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"campaign_recipients"}, []string{"campaign_id", "subscriber_id"}, &iteratorForBulkCreateCampaignRecipients{rows: arg})
}
