// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSubscriberToList = `-- name: AddSubscriberToList :exec
INSERT INTO list_subscribers (list_id, subscriber_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSubscriberToListParams struct {
	ListID       pgtype.UUID `json:"list_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) AddSubscriberToList(ctx context.Context, arg AddSubscriberToListParams) error {
	_, err := q.db.Exec(ctx, addSubscriberToList, arg.ListID, arg.SubscriberID)
	return err
}

const countSubscribersInList = `-- name: CountSubscribersInList :one
SELECT COUNT(*) FROM list_subscribers WHERE list_id = $1
`

func (q *Queries) CountSubscribersInList(ctx context.Context, listID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribersInList, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createList = `-- name: CreateList :one
INSERT INTO lists (name, description, double_opt_in)
VALUES ($1, $2, $3)
RETURNING id, name, description, double_opt_in, created_at, updated_at
`

type CreateListParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	DoubleOptIn bool   `json:"double_opt_in"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.Name, arg.Description, arg.DoubleOptIn)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DoubleOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const getListByID = `-- name: GetListByID :one
SELECT id, name, description, double_opt_in, created_at, updated_at FROM lists WHERE id = $1
`

func (q *Queries) GetListByID(ctx context.Context, id pgtype.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DoubleOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isSubscriberInList = `-- name: IsSubscriberInList :one
SELECT EXISTS(
    SELECT 1 FROM list_subscribers WHERE list_id = $1 AND subscriber_id = $2
)
`

type IsSubscriberInListParams struct {
	ListID       pgtype.UUID `json:"list_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) IsSubscriberInList(ctx context.Context, arg IsSubscriberInListParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSubscriberInList, arg.ListID, arg.SubscriberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLists = `-- name: ListLists :many
SELECT id, name, description, double_opt_in, created_at, updated_at FROM lists ORDER BY name ASC
`

func (q *Queries) ListLists(ctx context.Context) ([]List, error) {
	rows, err := q.db.Query(ctx, listLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DoubleOptIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListsForSubscriber = `-- name: ListListsForSubscriber :many
SELECT l.id, l.name, l.description, l.double_opt_in, l.created_at, l.updated_at FROM lists l
JOIN list_subscribers ls ON ls.list_id = l.id
WHERE ls.subscriber_id = $1
ORDER BY l.name
`

func (q *Queries) ListListsForSubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, listListsForSubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DoubleOptIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersInList = `-- name: ListSubscribersInList :many
SELECT s.id, s.email, s.first_name, s.last_name, s.status, s.source, s.created_at, s.updated_at FROM subscribers s
JOIN list_subscribers ls ON ls.subscriber_id = s.id
WHERE ls.list_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscribersInListParams struct {
	ListID pgtype.UUID `json:"list_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListSubscribersInList(ctx context.Context, arg ListSubscribersInListParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribersInList, arg.ListID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSubscriberFromList = `-- name: RemoveSubscriberFromList :exec
DELETE FROM list_subscribers WHERE list_id = $1 AND subscriber_id = $2
`

type RemoveSubscriberFromListParams struct {
	ListID       pgtype.UUID `json:"list_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) RemoveSubscriberFromList(ctx context.Context, arg RemoveSubscriberFromListParams) error {
	_, err := q.db.Exec(ctx, removeSubscriberFromList, arg.ListID, arg.SubscriberID)
	return err
}

const updateList = `-- name: UpdateList :one
UPDATE lists SET
    name          = $2,
    description   = $3,
    double_opt_in = $4,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, name, description, double_opt_in, created_at, updated_at
`

type UpdateListParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	DoubleOptIn bool        `json:"double_opt_in"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DoubleOptIn,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DoubleOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
