// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        pgtype.UUID
	KeyHash   string
	KeyPrefix string
	CreatedAt pgtype.Timestamptz
}

type Campaign struct {
	ID          pgtype.UUID
	Name        string
	Subject     string
	PreviewText string
	FromName    string
	FromEmail   string
	ReplyTo     string
	HtmlBody    string
	TextBody    string
	Status      string
	SendToType  string
	SendToID    pgtype.UUID
	ScheduledAt pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CampaignRecipient struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	SubscriberID pgtype.UUID
	Status       string
	SentAt       pgtype.Timestamptz
}

type Click struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	SubscriberID pgtype.UUID
	LinkIndex    int32
	LinkUrl      string
	ClickedAt    pgtype.Timestamptz
}

type List struct {
	ID          pgtype.UUID
	Name        string
	Description string
	DoubleOptIn bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ListSubscriber struct {
	ListID       pgtype.UUID
	SubscriberID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type Open struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	SubscriberID pgtype.UUID
	OpenedAt     pgtype.Timestamptz
}

type Owner struct {
	ID           bool
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SendJob struct {
	ID           pgtype.UUID
	CampaignID   pgtype.UUID
	Status       string
	TotalCount   int32
	SentCount    int32
	FailedCount  int32
	ErrorMessage string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Setting struct {
	ID              bool
	SetupComplete   bool
	SiteName        string
	InstallationUrl string
	Timezone        string
	PhysicalAddress string
	FromName        string
	FromEmail       string
	ReplyTo         string
	SmtpProvider    string
	SmtpCredentials []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Subscriber struct {
	ID        pgtype.UUID
	Email     string
	FirstName string
	LastName  string
	Status    string
	Source    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SubscriberTag struct {
	SubscriberID pgtype.UUID
	TagID        pgtype.UUID
}

type SuppressedEmail struct {
	ID        pgtype.UUID
	Email     string
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}
