// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpensByCampaign = `-- name: CountOpensByCampaign :one
SELECT COUNT(*) FROM opens WHERE campaign_id = $1
`

func (q *Queries) CountOpensByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpensByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalOpens = `-- name: CountTotalOpens :one
SELECT COUNT(*) FROM opens
`

func (q *Queries) CountTotalOpens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalOpens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasOpened = `-- name: HasOpened :one
SELECT EXISTS(
    SELECT 1 FROM opens WHERE campaign_id = $1 AND subscriber_id = $2
)
`

type HasOpenedParams struct {
	CampaignID   pgtype.UUID `json:"campaign_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) HasOpened(ctx context.Context, arg HasOpenedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpened, arg.CampaignID, arg.SubscriberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOpensBySubscriber = `-- name: ListOpensBySubscriber :many
SELECT id, campaign_id, subscriber_id, opened_at FROM opens WHERE subscriber_id = $1 ORDER BY opened_at DESC
`

func (q *Queries) ListOpensBySubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]Open, error) {
	rows, err := q.db.Query(ctx, listOpensBySubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Open
	for rows.Next() {
		var i Open
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SubscriberID,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOpen = `-- name: RecordOpen :exec
INSERT INTO opens (campaign_id, subscriber_id)
VALUES ($1, $2)
ON CONFLICT (campaign_id, subscriber_id) DO NOTHING
`

type RecordOpenParams struct {
	CampaignID   pgtype.UUID `json:"campaign_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

func (q *Queries) RecordOpen(ctx context.Context, arg RecordOpenParams) error {
	_, err := q.db.Exec(ctx, recordOpen, arg.CampaignID, arg.SubscriberID)
	return err
}
