// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: owner.sql

package db

import (
	"context"
)

const createOwner = `-- name: CreateOwner :one
INSERT INTO owner (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateOwnerParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, createOwner, arg.Email, arg.PasswordHash)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT id, email, password_hash, created_at, updated_at FROM owner WHERE id = TRUE
`

func (q *Queries) GetOwner(ctx context.Context) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwner)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOwnerPassword = `-- name: UpdateOwnerPassword :exec
UPDATE owner SET password_hash = $1, updated_at = NOW() WHERE id = TRUE
`

func (q *Queries) UpdateOwnerPassword(ctx context.Context, passwordHash string) error {
	_, err := q.db.Exec(ctx, updateOwnerPassword, passwordHash)
	return err
}
