// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: send_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSendJob = `-- name: CreateSendJob :one
INSERT INTO send_jobs (campaign_id) VALUES ($1) RETURNING id, campaign_id, status, total_count, sent_count, failed_count, error_message, created_at, updated_at
`

func (q *Queries) CreateSendJob(ctx context.Context, campaignID pgtype.UUID) (SendJob, error) {
	row := q.db.QueryRow(ctx, createSendJob, campaignID)
	var i SendJob
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.TotalCount,
		&i.SentCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSendJob = `-- name: GetSendJob :one
SELECT id, campaign_id, status, total_count, sent_count, failed_count, error_message, created_at, updated_at FROM send_jobs WHERE id = $1
`

func (q *Queries) GetSendJob(ctx context.Context, id pgtype.UUID) (SendJob, error) {
	row := q.db.QueryRow(ctx, getSendJob, id)
	var i SendJob
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.TotalCount,
		&i.SentCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSendJobByCampaign = `-- name: GetSendJobByCampaign :one
SELECT id, campaign_id, status, total_count, sent_count, failed_count, error_message, created_at, updated_at FROM send_jobs WHERE campaign_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetSendJobByCampaign(ctx context.Context, campaignID pgtype.UUID) (SendJob, error) {
	row := q.db.QueryRow(ctx, getSendJobByCampaign, campaignID)
	var i SendJob
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.TotalCount,
		&i.SentCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedCount = `-- name: IncrementFailedCount :exec
UPDATE send_jobs SET failed_count = failed_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementFailedCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedCount, id)
	return err
}

const incrementSentCount = `-- name: IncrementSentCount :exec
UPDATE send_jobs SET sent_count = sent_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementSentCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementSentCount, id)
	return err
}

const listPendingSendJobs = `-- name: ListPendingSendJobs :many
SELECT id, campaign_id, status, total_count, sent_count, failed_count, error_message, created_at, updated_at FROM send_jobs WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingSendJobs(ctx context.Context) ([]SendJob, error) {
	rows, err := q.db.Query(ctx, listPendingSendJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SendJob
	for rows.Next() {
		var i SendJob
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Status,
			&i.TotalCount,
			&i.SentCount,
			&i.FailedCount,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSendJobStatus = `-- name: UpdateSendJobStatus :exec
UPDATE send_jobs SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSendJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSendJobStatus(ctx context.Context, arg UpdateSendJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateSendJobStatus, arg.ID, arg.Status)
	return err
}
