// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, setup_complete, site_name, installation_url, timezone, physical_address, from_name, from_email, reply_to, smtp_provider, smtp_credentials, created_at, updated_at FROM settings WHERE id = TRUE
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SetupComplete,
		&i.SiteName,
		&i.InstallationUrl,
		&i.Timezone,
		&i.PhysicalAddress,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.SmtpProvider,
		&i.SmtpCredentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSetupComplete = `-- name: SetSetupComplete :exec
UPDATE settings SET setup_complete = TRUE, updated_at = NOW() WHERE id = TRUE
`

func (q *Queries) SetSetupComplete(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setSetupComplete)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings SET
    site_name        = $1,
    installation_url = $2,
    timezone         = $3,
    physical_address = $4,
    from_name        = $5,
    from_email       = $6,
    reply_to         = $7,
    smtp_provider    = $8,
    smtp_credentials = $9,
    updated_at       = NOW()
WHERE id = TRUE
RETURNING id, setup_complete, site_name, installation_url, timezone, physical_address, from_name, from_email, reply_to, smtp_provider, smtp_credentials, created_at, updated_at
`

type UpdateSettingsParams struct {
	SiteName        string `json:"site_name"`
	InstallationUrl string `json:"installation_url"`
	Timezone        string `json:"timezone"`
	PhysicalAddress string `json:"physical_address"`
	FromName        string `json:"from_name"`
	FromEmail       string `json:"from_email"`
	ReplyTo         string `json:"reply_to"`
	SmtpProvider    string `json:"smtp_provider"`
	SmtpCredentials []byte `json:"smtp_credentials"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.SiteName,
		arg.InstallationUrl,
		arg.Timezone,
		arg.PhysicalAddress,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.SmtpProvider,
		arg.SmtpCredentials,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SetupComplete,
		&i.SiteName,
		&i.InstallationUrl,
		&i.Timezone,
		&i.PhysicalAddress,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.SmtpProvider,
		&i.SmtpCredentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
