// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubscribers = `-- name: CountSubscribers :one
SELECT COUNT(*) FROM subscribers
`

func (q *Queries) CountSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (email, first_name, last_name, status, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, first_name, last_name, status, source, created_at, updated_at
`

type CreateSubscriberParams struct {
	Email     string
	FirstName string
	LastName  string
	Status    string
	Source    string
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.Source,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = $1
`

func (q *Queries) DeleteSubscriber(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, id)
	return err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, first_name, last_name, status, source, created_at, updated_at FROM subscribers WHERE email = $1
`

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, email, first_name, last_name, status, source, created_at, updated_at FROM subscribers WHERE id = $1
`

func (q *Queries) GetSubscriberByID(ctx context.Context, id pgtype.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, email, first_name, last_name, status, source, created_at, updated_at FROM subscribers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscribersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersByStatus = `-- name: ListSubscribersByStatus :many
SELECT id, email, first_name, last_name, status, source, created_at, updated_at FROM subscribers
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscribersByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListSubscribersByStatus(ctx context.Context, arg ListSubscribersByStatusParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubscribers = `-- name: SearchSubscribers :many
SELECT id, email, first_name, last_name, status, source, created_at, updated_at FROM subscribers
WHERE email ILIKE $1 OR first_name ILIKE $1 OR last_name ILIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchSubscribersParams struct {
	Email  string
	Limit  int32
	Offset int32
}

func (q *Queries) SearchSubscribers(ctx context.Context, arg SearchSubscribersParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, searchSubscribers, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriber = `-- name: UpdateSubscriber :one
UPDATE subscribers SET
    email      = $2,
    first_name = $3,
    last_name  = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, first_name, last_name, status, source, created_at, updated_at
`

type UpdateSubscriberParams struct {
	ID        pgtype.UUID
	Email     string
	FirstName string
	LastName  string
}

func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, updateSubscriber,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriberStatus = `-- name: UpdateSubscriberStatus :exec
UPDATE subscribers SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSubscriberStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateSubscriberStatus(ctx context.Context, arg UpdateSubscriberStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriberStatus, arg.ID, arg.Status)
	return err
}

const upsertSubscriber = `-- name: UpsertSubscriber :one
INSERT INTO subscribers (email, first_name, last_name, status, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (email) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name  = EXCLUDED.last_name,
    updated_at = NOW()
RETURNING id, email, first_name, last_name, status, source, created_at, updated_at
`

type UpsertSubscriberParams struct {
	Email     string
	FirstName string
	LastName  string
	Status    string
	Source    string
}

func (q *Queries) UpsertSubscriber(ctx context.Context, arg UpsertSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, upsertSubscriber,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.Source,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
