// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppressed_emails.sql

package db

import (
	"context"
)

const addSuppression = `-- name: AddSuppression :exec
INSERT INTO suppressed_emails (email, reason)
VALUES ($1, $2)
ON CONFLICT (email) DO NOTHING
`

type AddSuppressionParams struct {
	Email  string
	Reason string
}

func (q *Queries) AddSuppression(ctx context.Context, arg AddSuppressionParams) error {
	_, err := q.db.Exec(ctx, addSuppression, arg.Email, arg.Reason)
	return err
}

const countSuppressions = `-- name: CountSuppressions :one
SELECT COUNT(*) FROM suppressed_emails
`

func (q *Queries) CountSuppressions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSuppression = `-- name: DeleteSuppression :exec
DELETE FROM suppressed_emails WHERE email = $1
`

func (q *Queries) DeleteSuppression(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteSuppression, email)
	return err
}

const getSuppression = `-- name: GetSuppression :one
SELECT id, email, reason, created_at FROM suppressed_emails WHERE email = $1
`

func (q *Queries) GetSuppression(ctx context.Context, email string) (SuppressedEmail, error) {
	row := q.db.QueryRow(ctx, getSuppression, email)
	var i SuppressedEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS(SELECT 1 FROM suppressed_emails WHERE email = $1)
`

func (q *Queries) IsSuppressed(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isSuppressed, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT id, email, reason, created_at FROM suppressed_emails
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuppressionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]SuppressedEmail, error) {
	rows, err := q.db.Query(ctx, listSuppressions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressedEmail
	for rows.Next() {
		var i SuppressedEmail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
