// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToSubscriber = `-- name: AddTagToSubscriber :exec
INSERT INTO subscriber_tags (subscriber_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToSubscriberParams struct {
	SubscriberID pgtype.UUID `json:"subscriber_id"`
	TagID        pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToSubscriber(ctx context.Context, arg AddTagToSubscriberParams) error {
	_, err := q.db.Exec(ctx, addTagToSubscriber, arg.SubscriberID, arg.TagID)
	return err
}

const countSubscribersWithTag = `-- name: CountSubscribersWithTag :one
SELECT COUNT(*) FROM subscriber_tags WHERE tag_id = $1
`

func (q *Queries) CountSubscribersWithTag(ctx context.Context, tagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribersWithTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const isSubscriberTagged = `-- name: IsSubscriberTagged :one
SELECT EXISTS(SELECT 1 FROM subscriber_tags WHERE subscriber_id = $1 AND tag_id = $2)
`

type IsSubscriberTaggedParams struct {
	SubscriberID pgtype.UUID `json:"subscriber_id"`
	TagID        pgtype.UUID `json:"tag_id"`
}

func (q *Queries) IsSubscriberTagged(ctx context.Context, arg IsSubscriberTaggedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSubscriberTagged, arg.SubscriberID, arg.TagID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSubscribersWithTag = `-- name: ListSubscribersWithTag :many
SELECT s.id, s.email, s.first_name, s.last_name, s.status, s.source, s.created_at, s.updated_at FROM subscribers s
JOIN subscriber_tags st ON st.subscriber_id = s.id
WHERE st.tag_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscribersWithTagParams struct {
	TagID  pgtype.UUID `json:"tag_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListSubscribersWithTag(ctx context.Context, arg ListSubscribersWithTagParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribersWithTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForSubscriber = `-- name: ListTagsForSubscriber :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN subscriber_tags st ON st.tag_id = t.id
WHERE st.subscriber_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTagsForSubscriber(ctx context.Context, subscriberID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForSubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromSubscriber = `-- name: RemoveTagFromSubscriber :exec
DELETE FROM subscriber_tags WHERE subscriber_id = $1 AND tag_id = $2
`

type RemoveTagFromSubscriberParams struct {
	SubscriberID pgtype.UUID `json:"subscriber_id"`
	TagID        pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromSubscriber(ctx context.Context, arg RemoveTagFromSubscriberParams) error {
	_, err := q.db.Exec(ctx, removeTagFromSubscriber, arg.SubscriberID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $2 WHERE id = $1 RETURNING id, name, created_at
`

type UpdateTagParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
